
export const getReturnExchangeData = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        data: [
          {
            id: 1,
            orderedId: 'ORD123',
            returnedId: 'RET123',
            dateTime: '2024-11-20T12:30:00',
            invoiceAmount: '$100',
            acceptanceStatus: 'Accepted',
            returnRequired: 'Yes',
            adminStatus: 'Processed',
            reason: 'Damaged item',
            proof: 'Yes',
            moreDetails: 'No',
          },
          {
            id: 2,
            orderedId: 'ORD124',
            returnedId: 'RET124',
            dateTime: '2024-11-21T14:45:00',
            invoiceAmount: '$200',
            acceptanceStatus: 'Pending',
            returnRequired: 'No',
            adminStatus: 'Pending',
            reason: 'Wrong item received',
            proof: 'No',
            moreDetails: 'No',
          },
          {
            id: 3,
            orderedId: 'ORD125',
            returnedId: 'RET125',
            dateTime: '2024-11-22T09:15:00',
            invoiceAmount: '$150',
            acceptanceStatus: 'Accepted',
            returnRequired: 'Yes',
            adminStatus: 'Processed',
            reason: 'Item was too small',
            proof: 'Yes',
            moreDetails: 'No',
          },
          {
            id: 4,
            orderedId: 'ORD126',
            returnedId: 'RET126',
            dateTime: '2024-11-23T11:00:00',
            invoiceAmount: '$250',
            acceptanceStatus: 'Pending',
            returnRequired: 'Yes',
            adminStatus: 'Pending',
            reason: 'Color mismatch',
            proof: 'No',
            moreDetails: 'No',
          },
          {
            id: 5,
            orderedId: 'ORD127',
            returnedId: 'RET127',
            dateTime: '2024-11-24T13:30:00',
            invoiceAmount: '$300',
            acceptanceStatus: 'Accepted',
            returnRequired: 'No',
            adminStatus: 'Processed',
            reason: 'No longer needed',
            proof: 'Yes',
            moreDetails: 'No',
          },
          {
            id: 6,
            orderedId: 'ORD128',
            returnedId: 'RET128',
            dateTime: '2024-11-25T16:30:00',
            invoiceAmount: '$120',
            acceptanceStatus: 'Pending',
            returnRequired: 'Yes',
            adminStatus: 'Pending',
            reason: 'Wrong size',
            proof: 'No',
            moreDetails: 'No',
          },
          {
            id: 7,
            orderedId: 'ORD129',
            returnedId: 'RET129',
            dateTime: '2024-11-26T10:00:00',
            invoiceAmount: '$180',
            acceptanceStatus: 'Accepted',
            returnRequired: 'Yes',
            adminStatus: 'Processed',
            reason: 'Defective product',
            proof: 'Yes',
            moreDetails: 'No',
          },
          {
            id: 8,
            orderedId: 'ORD130',
            returnedId: 'RET130',
            dateTime: '2024-11-27T08:30:00',
            invoiceAmount: '$220',
            acceptanceStatus: 'Pending',
            returnRequired: 'No',
            adminStatus: 'Pending',
            reason: 'Not as described',
            proof: 'No',
            moreDetails: 'No',
          },
          {
            id: 9,
            orderedId: 'ORD131',
            returnedId: 'RET131',
            dateTime: '2024-11-28T17:15:00',
            invoiceAmount: '$90',
            acceptanceStatus: 'Accepted',
            returnRequired: 'Yes',
            adminStatus: 'Processed',
            reason: 'Damaged packaging',
            proof: 'Yes',
            moreDetails: 'No',
          },
          {
            id: 10,
            orderedId: 'ORD132',
            returnedId: 'RET132',
            dateTime: '2024-11-29T07:00:00',
            invoiceAmount: '$110',
            acceptanceStatus: 'Pending',
            returnRequired: 'Yes',
            adminStatus: 'Pending',
            reason: 'Wrong item shipped',
            proof: 'No',
            moreDetails: 'No',
          }
        ]
      });
    }, 1000); // Simulate network delay
  });
};
